### ISSUE TITLE
mAP: concatenated bbox column

### ISSUE THREAD

**Issue by willxxy** [moein-shariatnia/Pix2Seq#2]
Hello,

I have been trying to reimplement your evaluation code for mAP and it seems that the concatenated column is never created and I get a Key Error. 

![Screenshot from 2022-11-09 17-42-34](https://user-images.githubusercontent.com/90741489/200980315-c67be389-1d2b-4c7e-b268-9ab0c0aee1ee.png)

Here is the traceback of the error.
```

Traceback (most recent call last):
  File "/home/whan/hri/.env/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'concatenated'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/whan/hri/inference.py", line 134, in <module>
    target, detected = write_dfs2(gen_bboxes, gen_confs, gen_labels, test_df, id2cls)
  File "/home/whan/hri/utils.py", line 390, in write_dfs2
    target = df.explode('concatenated')[['id', 'concatenated', 'h', 'w']]
  File "/home/whan/hri/.env/lib/python3.9/site-packages/pandas/core/frame.py", line 8248, in explode
    result = df[columns[0]].explode()
  File "/home/whan/hri/.env/lib/python3.9/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/whan/hri/.env/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'concatenated'
```

**Comment by willxxy** [comment]
Hi I just noticed that you have a slightly different way of creating the dataset in this notebook. Will close this issue now.
